### ISSUE TITLE
Any plan to support verify in cloudflare workers/browser?

### ISSUE THREAD

**Issue by tiezhudotwang** [aws/aws-js-sns-message-validator#36]
I have a cloudflare workers to handle incoming sns message, now I run this verification in Lambda, does anyone know how to verify in workers/browser?

**Comment by devinstewart** [comment]
@tiezhudotwang - This issue as I see it is that this module relies on `crypto` included in Node.  And from what I have explored, the [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) does not have the need functionality to accomplish this.

That said, the required methods of `crypto` could be ported into JavaScript and served in one module.

I can work on something this week, I will leave a comment here when I have something with complete test coverage, which is extremely important when dealing with Cryptography.

**Full Disclosure:**  I do not work for AWS, I maintain [SNS Payload Validator](https://github.com/devinstewart/sns-payload-validator/), which is a module much like this, just in Post ES5 style and a few nice features.  This was asked of me once before, so if now two people have made an inquiry I guess there is a need.

**Comment by devinstewart** [comment]
@tiezhudotwang - Sorry for the wait.  Turns out [Web Crypto API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API) can validate a signature.  The wrinkle is that it expects a Public Key, and the SNS message provides a x509 Certificate.

That said there are a handful of libraries that can extract the Public Key from the Certificate, but they are usually larger modules that do all kinds for cryptography stuff.  One said package is [node-forge](https://github.com/digitalbazaar/forge), which I adapted the code from to do that extraction so I wouldn't be adding a 1.66 MB dependency.

After that there was the challenge of testing a Cloudflare worker locally and intercepting the `fecth()` call made inside of it to return a known x509 certificate.

All said and done I have a module 61.7 kB.  You can check it out on GitHub at: https://github.com/devinstewart/sns-cloudflare-validator or you can go straight to the [NPM](https://www.npmjs.com/package/sns-cloudflare-validator).

If you have any further questions feel free to open an issue in that repository.

**Comment by tiezhudotwang** [comment]
@devinstewart Wow, thank you for your work, this will cure my OCD (having to go to lambda just to verify a message is really frustrating)

**Comment by devinstewart** [comment]
@tiezhudotwang - Keep an eye out.  I'm going to be releasing a 1.0.1 this weekend.  (Nothing crazy just some code clean up / test coverage reporting)

Also while building this I thought of a feature that I am going to add to both of my modules.  The ability when initializing the `Validator` to specify:  `AWS Account ID`, `AWS Region`, and `Topic Name`, that you want to allow SNS payloads from.

While this is a stretch, I realized an attacker could create a real SNS topic that forwards to something harmless that just outputs the payload, then...  Takes that payload and sends it to you.  It's Valid!

You could do this yourself by looking at the `TopicArn` that is in the Payload, but seems to be in the scope of these modules.  Look for that in the coming weeks.

**Comment by tiezhudotwang** [comment]
@devinstewart 

Copy that. Also, to avoid my inaction affecting you, I feel I should mention that I recently noticed workers are constantly adding [node crypto implementations](https://developers.cloudflare.com/workers/runtime-apis/nodejs/crypto/#signverify). Since my project is a side project, I may not change it for now and will directly reimplement it using Cloudflare's interfaces after the Cloudflare team completes node crypto compatibility.

In any case, thank you so much for contributing your time to such a niche requirement.

**Comment by cloudkite** [comment]
please note that as of wrangler 4.4 the necessary crypto methods have been implemented. Only thing blocking this working with cloudflare workers now is https.get which could be changed to use fetch
